version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_Sofia1
    ports:
    - "3306:3306"
    volumes:
    - sofia_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"
    extra_hosts:
    - "host.docker.internal:host-gateway"
volumes:
  sofia_data: